### ISSUE TITLE
Remove Jekyll generated files and folders

### ISSUE THREAD

**Issue by nathanjessen** [octofi/octofidotcom#2]
Remove _site and ignore other files and folders generated by Jekyll. This prevents user or platform specific information from being shared.

https://jekyllrb.com/tutorials/using-jekyll-with-bundler/#commit-to-source-control

**Comment by nathanjessen** [comment]
Removing PR since it was getting too many conflicts from site updates.

`_site` directory should be removed from the repository and added to the `.gitignore`

**Comment by octofinance** [comment]
Thanks @nathanjessen, finally got around to [tidying up](https://github.com/octofi/octofidotcom/commit/46e5ccc595d612209838b6d5d7b7652fd1fc64d2) as per your recommendation. Much appreciated.
